version: 0.1
phases:
  install:
    commands:
      - echo installing nodejs...
      - npm install
      - npm install -g mocha
      - npm install -g serverless
      - echo nodejs installation done.
  build:
    commands:
      - echo deploying functions...
      - serverless deploy --stage dev | tee deploy.out
      - echo functions deployment done.