# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: hazardy-service-common

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  stage: dev
  apiKeys:
    - hazardy-api-${opt:stage, self:provider.stage}
  environment:
    cognito_identity_pool_id: poolid
    amazon_client_id: clientid
    amazon_client_secret:  abc
    service_authentication: hazardy-service-common-${opt:stage, self:provider.stage}-authentication
    region: self:provider.region
    hazard_table: hazard-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.hazard_table}"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "arn:aws:lambda:${opt:region, self:provider.region}:*:function:${self:provider.environment.service_authentication}"

functions: ${file(./src/config/functions.yml):functions}