# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: hazardy-service-api

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  stage: dev
  apiKeys:
    - hazardy-api-${opt:stage, self:provider.stage}
  environment:
    aws_account_id: accountid
    cognito_identity_pool_id: poolid
    iam_role_arn: arn
    cognito_dataset_name: dataset
    cognito_key_name: key
    callbackurl: url
    amazon_client_id: clientid
    amazon_client_secret:  ${client_secret}
    service_authentication: hazardy-service-common-${opt:stage, self:provider.stage}-authentication
    region: ap-southeast-2
    vehicle_table: vehicle-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.vehicle_table}"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "arn:aws:lambda:${opt:region, self:provider.region}:*:function:${self:provider.environment.service_authentication}"

functions: ${file(./src/config/functions.yml):functions}