functions:
  login:
    handler: src/handlers.authenticate
    events:
      - http:
          path: /v1/authenticate
          method: get
          cors: true
          private: true
  getHazardsByCompanyId:
    handler: src/handlers.getHazardsByCompanyId
    events:
      - http:
          path: /v1/hazards
          method: get
          request:
            parameters:
              querystrings:
                companyId: true
          cors: true
          private: true
  getHazardById:
    handler: src/handlers.getHazardById
    events:
      - http:
          path: /v1/hazards/{hazardId}
          method: get
          cors: true
          private: true