functions:
  login:
    handler: src/handlers.authenticate
    events:
      - http:
          path: /v1/authenticate
          method: post
          cors: true
          private: true
  getHazardsByUserId:
    handler: src/handlers.getHazardsByUserId
    events:
      - http:
          path: /v1/hazards
          method: get
          request:
            parameters:
              querystrings:
                userId: true
          cors: true
          private: true
  getHazardById:
    handler: src/handlers.getHazardById
    events:
      - http:
          path: /v1/hazards/{hazardId}
          method: get
          cors: true
          private: true