functions:
  login:
    handler: src/handlers.login
    events:
      - http:
          path: /v1/login
          method: get
          cors: true
          private: true
  getVehicles:
    handler: src/handlers.getVehiclesByCompanyId
    events:
      - http:
          path: /v1/vehicles
          method: get
          request:
            parameters:
              querystrings:
                companyId: true
          cors: true
          private: true
  getVehicleById:
    handler: src/handlers.getVehicleById
    events:
      - http:
          path: /v1/vehicles/{vehicleId}
          method: get
          cors: true
          private: true